# YOLO Params
Yolo/cfg_path                           : [Absolute Path]/far-planner-with-yolo/src/yolo/data/yolov4-tiny.cfg
Yolo/weight_path                        : [Absolute Path]/far-planner-with-yolo/src/yolo/data/yolov4-tiny.weights
Yolo/coconame_path                      : [Absolute Path]/far-planner-with-yolo/src/yolo/data/coco.names
